# Generated by Django 6.1 on 2026-09-02 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=255)),
                ('icon', models.CharField(blank=True, help_text="Optional short label/emoji used as a simple icon, e.g. '✿'.", max_length=50)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'About Feature',
                'verbose_name_plural': 'About Features',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('subject', models.CharField(max_length=150)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Contact Message',
                'verbose_name_plural': 'Contact Messages',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_name', models.CharField(default='Miracle Flowers', max_length=150)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='site/')),
                ('hero_image', models.ImageField(blank=True, null=True, upload_to='site/')),
                ('hero_tagline', models.CharField(default="Beautiful flowers for life's beautiful moments.", max_length=200)),
                ('hero_subtext', models.TextField(default='Miracle Flowers provides beautiful floral arrangements for celebrations, special occasions, events, and everyday moments.')),
                ('phone_number', models.CharField(default='+254 700 000 000', max_length=30)),
                ('email', models.EmailField(default='hello@miracleflowers.co.ke', max_length=254)),
                ('address', models.CharField(default='Argwings Kodhek Road, Nairobi, Kenya', max_length=255)),
                ('opening_hours', models.CharField(default='Mon – Sat: 8:00 AM – 7:00 PM, Sun: 10:00 AM – 4:00 PM', max_length=255)),
                ('featured_flowers_count', models.PositiveIntegerField(default=6, help_text="How many flowers to show in the homepage 'Featured Flowers' section.")),
                ('facebook_url', models.URLField(blank=True)),
                ('instagram_url', models.URLField(blank=True)),
                ('whatsapp_number', models.CharField(blank=True, max_length=30)),
                ('about_text', models.TextField(default='Miracle Flowers began with a simple belief: that flowers have the power to turn ordinary moments into unforgettable ones. From weddings and graduations to a quiet Tuesday that deserves a little brightness, our florists hand-craft every arrangement with care, freshness, and an eye for detail.')),
                ('mission_text', models.TextField(default="Our mission is to deliver fresh, thoughtfully designed floral arrangements and unforgettable event experiences that help our customers celebrate life's most meaningful moments.")),
                ('footer_text', models.CharField(default='Premium flowers and floral experiences for every occasion.', max_length=255)),
                ('is_active', models.BooleanField(default=True, help_text='Only one SiteSettings record should be active at a time.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Site Settings',
                'verbose_name_plural': 'Site Settings',
            },
        ),
    ]
