# Generated by Django 6.1 on 2026-09-14 08:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flowers', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='flowerimage',
            options={'ordering': ['order', 'id'], 'verbose_name': 'Flower Gallery Image', 'verbose_name_plural': 'Flower Gallery Images'},
        ),
        migrations.AlterField(
            model_name='flower',
            name='short_description',
            field=models.CharField(help_text='Short description shown on flower cards.', max_length=200),
        ),
        migrations.AlterField(
            model_name='flowerimage',
            name='flower',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_images', to='flowers.flower'),
        ),
        migrations.AddIndex(
            model_name='flower',
            index=models.Index(fields=['available'], name='flowers_flo_availab_6c3b2a_idx'),
        ),
        migrations.AddIndex(
            model_name='flower',
            index=models.Index(fields=['featured'], name='flowers_flo_feature_ec7dce_idx'),
        ),
        migrations.AddIndex(
            model_name='flower',
            index=models.Index(fields=['category'], name='flowers_flo_categor_a98e4e_idx'),
        ),
        migrations.AddIndex(
            model_name='flowerimage',
            index=models.Index(fields=['flower', 'order'], name='flowers_flo_flower__e7f635_idx'),
        ),
    ]
